# %README%: see the clamav README file. 
clamav
perl-extutils-pkgconfig
perl-extutils-depends
perl-glib
perl-cairo
perl-pango
perl-gtk2
perl-Text-Glob
perl-Number-Compare
perl-File-Find-Rule
perl-net-ip
perl-digest-sha1
perl-digest-hmac
perl-net-dns
perl-Sub-Uplevel
perl-Test-Exception
perl-Carp-Clan
perl-Bit-Vector
perl-Date-Calc
locale-gettext
perl-www-robotrules
perl-net-http
perl-IO-HTML
perl-lwp-mediatypes
perl-http-date
perl-html-tagset
perl-html-parser
perl-encode-locale
perl-http-message
perl-http-negotiate
perl-http-daemon
perl-http-cookies
perl-file-listing
libwww-perl
clamtk
