ghc
haskell-extensible-exceptions
haskell-text
haskell-xml
haskell-transformers
haskell-mtl
haskell-regex-base
haskell-regex-posix
haskell-random
haskell-hostname
haskell-ansi-terminal
haskell-ansi-wl-pprint
haskell-test-framework
haskell-HUnit
haskell-test-framework-hunit
