ghc
haskell-extensible-exceptions
haskell-text
haskell-transformers
haskell-mtl
haskell-parsec
haskell-network
haskell-HTTP
haskell-xml
haskell-syb
haskell-texmath
haskell-regex-base
haskell-regex-pcre-builtin
haskell-blaze-builder
haskell-blaze-markup
haskell-blaze-html
haskell-highlighting-kate
haskell-utf8-string
haskell-pandoc-types
haskell-json
haskell-citeproc-hs
haskell-tagsoup
haskell-zlib
haskell-digest
haskell-zip-archive
haskell-temporary
haskell-random
haskell-dlist
haskell-data-default
haskell-base64-bytestring
pandoc
