perl-www-robotrules
perl-net-http
perl-IO-HTML
perl-lwp-mediatypes
perl-http-date
perl-html-tagset
perl-html-parser
perl-encode-locale
perl-http-message
perl-http-negotiate
perl-http-daemon
perl-http-cookies
perl-file-listing
libwww-perl
perl-HTTP-Proxy
