perl-x11-protocol
perl-tree-dagnode
perl-Sub-Uplevel
perl-test-warn
perl-http-server-simple
perl-www-robotrules
perl-net-http
perl-IO-HTML
perl-lwp-mediatypes
perl-http-date
perl-html-tagset
perl-html-parser
perl-encode-locale
perl-http-message
perl-http-negotiate
perl-http-daemon
perl-http-cookies
perl-file-listing
libwww-perl
perl-http-response-encoding
perl-html-form
perl-www-mechanize
perl-proc-processtable
perl-xml-twig
perl-net-dbus
perl-extutils-pkgconfig
perl-extutils-depends
perl-glib
perl-cairo
perl-pango
perl-gtk2
gtkimageview
perl-gtk2-imageview
perl-gnome2-wnck
perl-gnome2-gconf
ORBit2
libbonobo
gnome-mime-data
gnome-vfs
perl-gnome2-vfs
libgnomecanvas
perl-gnome2-canvas
libgnome
libbonoboui
libgnomeui
perl-gnome2
locale-gettext
shutter
