re2c
pyzor
perl-Net-Server
perl-Net-Ident
perl-net-ip
perl-digest-sha1
perl-digest-hmac
perl-net-dns
perl-NetAddr-IP
perl-Net-DNS-Resolver-Programmable
perl-Mail-SPF
perl-TimeDate
perl-MailTools
perl-Crypt-OpenSSL-Random
perl-Crypt-OpenSSL-RSA
perl-Mail-DKIM
perl-Image-Info
perl-Geography-Countries
perl-IP-Country
perl-Net-LibIDN
Net-SSLeay
perl-IO-Socket-SSL
perl-Socket6
perl-IO-Socket-INET6
perl-Encode-Detect
perl-Crypt-OpenSSL-Bignum
perl-www-robotrules
perl-net-http
perl-IO-HTML
perl-lwp-mediatypes
perl-http-date
perl-html-tagset
perl-html-parser
perl-encode-locale
perl-http-message
perl-http-negotiate
perl-http-daemon
perl-http-cookies
perl-file-listing
libwww-perl
spamassassin
